[theme]
# Clean, modern theme
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
# Performance settings
maxUploadSize = 200
enableCORS = false
enableXsrfProtection = false

[browser]
# UI settings
gatherUsageStats = false
